### PR TITLE
some small perf improvements

### PR DESCRIPTION
**Pull request by connyduck**
please review
I am not sure why the animator is started in setVisibility when the new visibility is not VISIBLE.

### CODE REVIEW

**Comment by kofigyan** [comment]
I will review this and get back to you. Thank you.

**Comment by kofigyan** [comment]
Hi @connyduck , l noted the changes to the FontManager class. I decided to cache the Typeface in HashMap because of [this](https://code.google.com/p/android/issues/detail?id=9904) reported bug with the call of Typeface.createFromAsset(). 
    Thanks again for this important pull request.

**Comment by connyduck** [comment]
Thanks for merging! We are in the process of optimizing our app, so I decided to have a look at its libraries as well. This helps a lot, thank you!

**Comment by kofigyan** [comment]
You're welcome.

**Pull request merged**
