### PR TITLE
Change AllowBackup from Manifest

### PR DESCRIPTION
**Pull request by pacdouglas**
I'm in a project that goes through a security and vunerability tool which one of the requirements is the flag "AllowBackup" of the manifest file to have the value "false". I forked your project and changed that flag. Thanks a lot! I'm also making this "Pull Request" in case you find it interesting and want to make it default so people don't have this problem again.

### CODE REVIEW

**Comment by connyduck** [comment]
yes this is a good idea, please merge it @kofigyan 
And you should probably put *.iml files and files under .idea into gitignore :)

**Comment by pacdouglas** [comment]
Ye, sorry about *iml and .idea files ^_^

**Comment by ligol** [comment]
There is no need for an application tag in the manifest, could be better to simply delete it, what do you think?

**Comment by kofigyan** [comment]
Thank you @pacdouglas , @connyduck and @ligol  and sorry about the delay in response. I am currently looking at this PR and will merge soon.

**Comment by ligol** [comment]
Merging the #3 PR will fix this issue by the way

**Comment by kofigyan** [comment]
Is merged now. Thanks once again  @pacdouglas , @connyduck and @ligol .

**Pull request merged**
